version: "3.8"

services:

  accounts:
    image: afrid98/bank-accounts:latest
    ports:
      - "8080:8080"
    networks:
      -  afrid98-network

  loans:
    image: afrid98/loan:latest
    ports:
      - "8090:8090"
    networks:
      -  afrid98-network

  cards:
    image: afrid98/cards:latest
    ports:
      - "9000:9000"
    networks:
      -  afrid98-network

networks:
   afrid98-network: