version: "3.8"

services:

  config-server:
    image: afrid98/config-server:latest
    ports:
      - "8071:8071"
    networks:
      - afrid98-network
  accounts:
    image: afrid98/bank-accounts:latest
    ports:
      - "8080:8080"
    networks:
      -  afrid98-network
    depends_on:
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_SERVER: configserver:http://configserver:8071

  loans:
    image: afrid98/loan:latest
    ports:
      - "8090:8090"
    networks:
      -  afrid98-network
    depends_on:
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_SERVER: configserver:http://configserver:8071

  cards:
    image: afrid98/cards:latest
    ports:
      - "9000:9000"
    networks:
      -  afrid98-network
    depends_on:
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_SERVER: configserver:http://configserver:8071

networks:
   afrid98-network: